import search

def readfile_test():
    assert search.readfile("text_example_1.txt") == ['While the Congress of the Republic endlessly debates', 'this alarming chain of events, the Supreme Chancellor has', 'secretly dispatched two Jedi Knights.']
    assert search.readfile("text_example_2.txt") == ['Le fondateur de la collection est Paul Faucher (1898-1967),', "pionnier de l'éducation nouvelle, qui avait en 1927 lancé la collection", "« Éducation » chez Flammarion. C'était un passionné des thèses de la pédagogue tchécoslovaque", 'Lida Durdikova et de son compatriote associé František Bakule. Lida Durdikova a signé des', 'albums du Père Castor du seul nom de Lida ; elle épousera Paul Faucher en 19321.', "Rompant avec la conception traditionnelle de l'album artistique cartonné, conçu comme un", "cadeau d'étrennes où l'art ne s'émancipe pas du luxe, Faucher destine sa collection à tous les", "enfants, si bien qu'il est rapidement soutenu par l'institution scolaire. Ses albums sur papier", "ont une couverture souple et des pages agrafées qui désacralisent l'objet livre. Ils ont des", 'formats variés selon leurs objectifs littéraires et graphiques. Faucher fait appel à des illustrateurs de', 'grand talent, dont certains sont situés dans la mouvance des avant-gardes russes : Hélène Guertik, Fiodor', 'Rojankovski, Alexandra Exter, Nathalie Parain, G. Tcherkessof, N. Altman et Ivan Bilibine2.', "En 1946, après la parution d'une centaine d'albums, Paul Faucher ouvre le Centre de recherche", "biblio-pédagogique de l'atelier du père Castor et, l'année suivante, l'école du Père Castor1."]

def get_words_test():
    assert search.get_words("While the Congress of the Republic endlessly debates") == ['while', 'the', 'congress', 'of', 'the', 'republic', 'endlessly', 'debates']
    assert search.get_words("pionnier de l'éducation nouvelle, qui avait en 1927 lancé la collection") == ['pionnier', 'de', 'léducation', 'nouvelle', 'qui', 'avait', 'en', '1927', 'lancé', 'la', 'collection']

def create_index_test():
    assert search.create_index("text_example_1.txt") == {'while': [0], 'the': [0, 1], 'congress': [0], 'of': [0, 1], 'republic': [0], 'endlessly': [0], 'debates': [0], 'this': [1], 'alarming': [1], 'chain': [1], 'events': [1], 'supreme': [1], 'chancellor': [1], 'has': [1], 'secretly': [2], 'dispatched': [2], 'two': [2], 'jedi': [2], 'knights': [2]}
    assert search.create_index("text_example_2.txt") == {'le': [0, 12], 'fondateur': [0], 'de': [0, 1, 2, 3, 4, 5, 9, 12, 13], 'la': [0, 1, 2, 5, 10, 12], 'collection': [0, 1, 6], 'est': [0, 7], 'paul': [0, 4, 12], 'faucher': [0, 4, 6, 9, 12], '18981967': [0], 'pionnier': [1], 'léducation': [1], 'nouvelle': [1], 'qui': [1, 8], 'avait': [1], 'en': [1, 4, 12], '1927': [1], 'lancé': [1], 'éducation': [2], 'chez': [2], 'flammarion': [2], 'cétait': [2], 'un': [2, 5], 'passionné': [2], 'des': [2, 3, 8, 9, 10], 'thèses': [2], 'pédagogue': [2], 'tchécoslovaque': [2], 'lida': [3, 4], 'durdikova': [3], 'et': [3, 8, 9, 11, 13], 'son': [3], 'compatriote': [3], 'associé': [3], 'františek': [3], 'bakule': [3], 'a': [3], 'signé': [3], 'albums': [4, 7], 'du': [4, 6, 13], 'père': [4, 13], 'castor': [4, 13], 'seul': [4], 'nom': [4], 'elle': [4], 'épousera': [4], '19321': [4], 'rompant': [5], 'avec': [5], 'conception': [5], 'traditionnelle': [5], 'lalbum': [5], 'artistique': [5], 'cartonné': [5], 'conçu': [5], 'comme': [5], 'cadeau': [6], 'détrennes': [6], 'où': [6], 'lart': [6], 'ne': [6], 'sémancipe': [6], 'pas': [6], 'luxe': [6], 'destine': [6], 'sa': [6], 'à': [6, 9], 'tous': [6], 'les': [6], 'enfants': [7], 'si': [7], 'bien': [7], 'quil': [7], 'rapidement': [7], 'soutenu': [7], 'par': [7], 'linstitution': [7], 'scolaire': [7], 'ses': [7], 'sur': [7], 'papier': [7], 'ont': [8], 'une': [8], 'couverture': [8], 'souple': [8], 'pages': [8], 'agrafées': [8], 'désacralisent': [8], 'lobjet': [8], 'livre': [8], 'ils': [8], 'formats': [9], 'variés': [9], 'selon': [9], 'leurs': [9], 'objectifs': [9], 'littéraires': [9], 'graphiques': [9], 'fait': [9], 'appel': [9], 'illustrateurs': [9], 'grand': [10], 'talent': [10], 'dont': [10], 'certains': [10], 'sont': [10], 'situés': [10], 'dans': [10], 'mouvance': [10], 'avantgardes': [10], 'russes': [10], 'hélène': [10], 'guertik': [10], 'fiodor': [10], 'rojankovski': [11], 'alexandra': [11], 'exter': [11], 'nathalie': [11], 'parain': [11], 'g': [11], 'tcherkessof': [11], 'n': [11], 'altman': [11], 'ivan': [11], 'bilibine2': [11], '1946': [12], 'après': [12], 'parution': [12], 'dune': [12], 'centaine': [12], 'dalbums': [12], 'ouvre': [12], 'centre': [12], 'recherche': [12], 'bibliopédagogique': [13], 'latelier': [13], 'lannée': [13], 'suivante': [13], 'lécole': [13], 'castor1': [13]}

def get_lines_test():
    assert search.get_lines(["the","of"],{'while': [0], 'the': [0, 1], 'congress': [0], 'of': [0, 1], 'republic': [0], 'endlessly': [0], 'debates': [0], 'this': [1], 'alarming': [1], 'chain': [1], 'events': [1], 'supreme': [1], 'chancellor': [1], 'has': [1], 'secretly': [2], 'dispatched': [2], 'two': [2], 'jedi': [2], 'knights': [2]}) == [0,1]
    assert search.get_lines(["de","la"],{'le': [0, 12], 'fondateur': [0], 'de': [0, 1, 2, 3, 4, 5, 9, 12, 13], 'la': [0, 1, 2, 5, 10, 12], 'collection': [0, 1, 6], 'est': [0, 7], 'paul': [0, 4, 12], 'faucher': [0, 4, 6, 9, 12], '18981967': [0], 'pionnier': [1], 'léducation': [1], 'nouvelle': [1], 'qui': [1, 8], 'avait': [1], 'en': [1, 4, 12], '1927': [1], 'lancé': [1], 'éducation': [2], 'chez': [2], 'flammarion': [2], 'cétait': [2], 'un': [2, 5], 'passionné': [2], 'des': [2, 3, 8, 9, 10], 'thèses': [2], 'pédagogue': [2], 'tchécoslovaque': [2], 'lida': [3, 4], 'durdikova': [3], 'et': [3, 8, 9, 11, 13], 'son': [3], 'compatriote': [3], 'associé': [3], 'františek': [3], 'bakule': [3], 'a': [3], 'signé': [3], 'albums': [4, 7], 'du': [4, 6, 13], 'père': [4, 13], 'castor': [4, 13], 'seul': [4], 'nom': [4], 'elle': [4], 'épousera': [4], '19321': [4], 'rompant': [5], 'avec': [5], 'conception': [5], 'traditionnelle': [5], 'lalbum': [5], 'artistique': [5], 'cartonné': [5], 'conçu': [5], 'comme': [5], 'cadeau': [6], 'détrennes': [6], 'où': [6], 'lart': [6], 'ne': [6], 'sémancipe': [6], 'pas': [6], 'luxe': [6], 'destine': [6], 'sa': [6], 'à': [6, 9], 'tous': [6], 'les': [6], 'enfants': [7], 'si': [7], 'bien': [7], 'quil': [7], 'rapidement': [7], 'soutenu': [7], 'par': [7], 'linstitution': [7], 'scolaire': [7], 'ses': [7], 'sur': [7], 'papier': [7], 'ont': [8], 'une': [8], 'couverture': [8], 'souple': [8], 'pages': [8], 'agrafées': [8], 'désacralisent': [8], 'lobjet': [8], 'livre': [8], 'ils': [8], 'formats': [9], 'variés': [9], 'selon': [9], 'leurs': [9], 'objectifs': [9], 'littéraires': [9], 'graphiques': [9], 'fait': [9], 'appel': [9], 'illustrateurs': [9], 'grand': [10], 'talent': [10], 'dont': [10], 'certains': [10], 'sont': [10], 'situés': [10], 'dans': [10], 'mouvance': [10], 'avantgardes': [10], 'russes': [10], 'hélène': [10], 'guertik': [10], 'fiodor': [10], 'rojankovski': [11], 'alexandra': [11], 'exter': [11], 'nathalie': [11], 'parain': [11], 'g': [11], 'tcherkessof': [11], 'n': [11], 'altman': [11], 'ivan': [11], 'bilibine2': [11], '1946': [12], 'après': [12], 'parution': [12], 'dune': [12], 'centaine': [12], 'dalbums': [12], 'ouvre': [12], 'centre': [12], 'recherche': [12], 'bibliopédagogique': [13], 'latelier': [13], 'lannée': [13], 'suivante': [13], 'lécole': [13], 'castor1': [13]}) == [0, 1, 2, 4, 5, 12]

readfile_test()
get_words_test()
create_index_test()
get_lines_test()

